dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'

os:
  - linux

cache: pip

install: 
  - pip install -r pin-manager-bot/requirements.txt
  - chmod +x pin-manager-bot/qa.sh

script: ./pin-manager-bot/qa.sh

